name = "kungen-hoppar-flaggor"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "kungen-db"
database_id = "your-database-id-here"

# För utveckling (local)
[env.dev]
[[env.dev.d1_databases]]
binding = "DB"
database_name = "kungen-db"
preview_database_id = "local" 