name = "kungen-hoppar-flaggor"
main = "worker.js"
compatibility_date = "2024-01-01"

[assets]
directory = "./static"
binding = "ASSETS"

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "kungen-db"
database_id = "2f67300d-d84e-43ee-9f87-9ded60869e8a"

# För utveckling (local)
[env.dev]
[[env.dev.d1_databases]]
binding = "DB"
database_name = "kungen-db"
preview_database_id = "local" 